### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by jyothishnt**
Moving from master to main

### CODE REVIEW

**Review by jgtate — APPROVED** [review]

**Review by nwillhoft — APPROVED** [review]
These changes renaming the `master` branch to `main` look good and do not appear to affect/break Infrastructure-related repos

**Comment by azangru** [comment]
@nwillhoft are you still running Travis for anything in this repo? We were wondering, during code review, whether the `.travis.yml` file is still used by anything.

**Comment by nwillhoft** [comment]
> @nwillhoft are you still running Travis for anything in this repo? We were wondering, during code review, whether the `.travis.yml` file is still used by anything.

Hi, I've asked the team and Mira has confirmed that we aren't running Travis for anything in this repo.

**Comment by Mehrnaz-Charkhchi** [comment]
> > @nwillhoft are you still running Travis for anything in this repo? We were wondering, during code review, whether the `.travis.yml` file is still used by anything.
> 
> Hi, I've asked the team and Mira has confirmed that we aren't running Travis for anything in this repo.

Hi, Thank you for confirming I'm gonna merge the PR.

**Pull request merged**
