### PR TITLE
Feature/biodbhts

### PR DESCRIPTION
**Pull request by rishidev**
The Faidx XS module is now integrated into Bio::DB::HTS (https://github.com/Ensembl/Bio-HTS). The upgrades have been made to make the install script setup Bio::DB::HTS and refer to the Bio::DB::HTS::Faidx class rather than Faidx. Now with added Travis CI updates.

### CODE REVIEW

**Comment by willmclaren** [comment]
I'm not sure this is working still.

I run INSTALL.pl and it finishes OK.

Then I tried this in the same directory:

`> perl -MBio::DB::HTS
Can't load './HTS.so' for module Bio::DB::HTS: libhts.so.1: cannot open shared object file: No such file or directory at /software/ensembl/central/lib/5.14.2/x86_64-linux-thread-multi/DynaLoader.pm line 190.
 at - line 0.
Compilation failed in require.
BEGIN failed--compilation aborted.`

This should work, no?

The following works with the old thing:

`perl -MFaidx`

**Comment by rishidev** [comment]
It runs (without the -M flag for invocation) with the LD_LIBRARY_PATH being set to include the location of libhts.so.1, as it is for Macs. I'll have a check and update the script to prompt for this being set. I'm not 100% sure why this is not being picked up as it was for Faidx also.

**Comment by lairdm** [comment]
Are you open to the suggestion of pointing the PERL5LIB at the blib/arch directory in Bio-HTS rather than copying the two .so? It keeps things a little cleaner rather than .so files floating around in various places.

**Comment by rishidev** [comment]
Yes, that is one of the things I want to check out. We did it with Faidx to keep things simpler for the end user, but it might be the way to go here.

**Comment by lairdm** [comment]
Oh I'm almost done something to potentially help with that... ;)

**Comment by rishidev** [comment]
OK - I've added in the prompts. I've tried various combinations and feel copying the .so files and giving the user shorter prompts to update their paths with would be better, particularly when doing an installation with DEST_DIR specified. The invocation no longer needs the -M flag. It needs the new ensembl-variation in place to pass tests and for FAIDX to work.

**Comment by willmclaren** [comment]
Sorry, still the same issue @rishidev 

perl -MBio::DB::HTS
Can't load './HTS.so' for module Bio::DB::HTS: libhts.so.1: cannot open shared object file: No such file or directory at /software/ensembl/central/lib/5.14.2/x86_64-linux-thread-multi/DynaLoader.pm line 190.
 at - line 0.
Compilation failed in require.
BEGIN failed--compilation aborted.

This is on a Sanger farm head node, not my Mac.

**Comment by rishidev** [comment]
@willmclaren What do you have the LD_LIBRARY_PATH value set to? The -M flag should not be required anymore.

**Comment by willmclaren** [comment]
I didn't set LD_LIBRARY_PATH - there was no instruction to do so. And I don't think I should have to, you're setting arbitrary barriers for users (and me) here which will annoy them.

This worked fine with the Faidx thing last release, I don't see why it has to be any different now.

**Comment by lairdm** [comment]
From what I can see in the package, during the "perl Build.PL <htslib_dir>" step the htslib_dir is used for linking during build (-L<htslib_dir>), but that path isn't stashed away for loading. So if htslib_dir isn't either in LD_LIBRARY_PATH or installed somewhere ld.conf knows about, yes it won't be found. It's been years since I've played with the DynaLoader, but during the runtime could htslib_dir not be pushed in to @dl_library_path just before the bootstrap call so the shared library can be found. Of course this is slightly fragile if the user moved htslib_dir elsewhere, then either rebuilding or LD_LIBRARY_PATH would be needed.

**Comment by rishidev** [comment]
The lack of prompt for it being set was an error, so have fixed that, though it will be removed if the LD_LIBRARY_PATH setting can be avoided. The Faidx library had a different build setup and this seemed to store the htslib location whereas Bio::DB::HTS was adapted from Bio-Samtools and uses the Module::Build setup. Will have a look at if this can be used to setup for runtime access.

**Comment by rishidev** [comment]
There is a -rpath flag in the linking step that gets specified using ExtUtils::MakeMaker which was why it got hardcoded in that library. Should be able to bring this across into the Module::Build, so it will behave as before.

**Comment by rishidev** [comment]
The updates to the build and the installer have been made, so it should work without LD_LIBRARY_PATH being set on Linux.

**Comment by willmclaren** [comment]
Cool everything looking good now.

Will run a few more tests before merging.

Thanks for your efforts with this.

**Comment by willmclaren** [comment]
I've merged this in manually as it needed a minor rebase due to a interim commit.

**Pull request closed without merging**
