### PR TITLE
Feature/biodbhts

### PR DESCRIPTION
**Pull request by rishidev**
The Faidx XS module is now integrated into Bio::DB::HTS (https://github.com/Ensembl/Bio-HTS). The upgrades have been made to make the install script setup  Bio::DB::HTS and refer to the Bio::DB::HTS::Faidx class rather than Faidx.

A separate pull request has been made for ensembl-variation with which these changes have been tested. (https://github.com/Ensembl/ensembl-variation/pull/25)

### CODE REVIEW

**Comment by magaliruffier** [comment]
is this going to affect the REST VEP endpoints and installation, which are currently using Faidx?

**Comment by rishidev** [comment]
From the front end the install scripts run the same, it just leaves Bio::DB::HTS repo present. 

From a coding level things that are Faidx should be Bio::DB::HTS::Faidx so if the endpoint code uses this it will need to be updated. 

One other thing to through into the mix I guess is the availability of installing via CPAN directly - the average VEP user wouldn't have sudo access so I went with this, but it may offer another avenue.

**Comment by andrewyatz** [comment]
Going via CPAN is more viable for REST installations TBH

**Comment by rishidev** [comment]
Makes sense - I can add a flag to the installer to assume htslib and Bio::DB::HTS are already installed.

**Comment by andrewyatz** [comment]
I didn't think REST installations would even be going via the ensembl-tools script. Unless I've missed the point.

**Comment by magaliruffier** [comment]
We don't use the ensembl-tools install script, but if the change affects VEP, we need to update the REST installation documentation and code
The main places I can think of are:
https://github.com/Ensembl/ensembl-rest/blob/master/.travis.yml
and
https://github.com/Ensembl/ensembl-rest/blob/master/lib/EnsEMBL/REST/Controller/VEP.pm#L417

**Comment by rishidev** [comment]
The existing NO_HTSLIB allows the skipping of installation and but is not separate from attempts to convert and index downloaded compressed FASTA files.

**Comment by rishidev** [comment]
Yes, both of those ensembl-rest files will need an update - will make the changes and send them through.

**Comment by magaliruffier** [comment]
Thanks
I'll leave this PR to @willmclaren

**Comment by willmclaren** [comment]
Also the .travis.yml file https://github.com/Ensembl/ensembl-tools/blob/master/.travis.yml is still installing Faidx

**Comment by rishidev** [comment]
I've got the changes to the REST API good to make a pull request at 
https://github.com/rishidev/ensembl-rest/tree/feature/faidx_to_biodbhts
when these changes are in place.

**Comment by willmclaren** [comment]
INSTALL.pl fails for me:

 - checking out HTSLib
fatal: destination path 'htslib' already exists and is not an empty directory.
 - building HTSLIB in ./htslib
In [path]/ensembl-tools/scripts/variant_effect_predictor/htslib
make: Nothing to be done for `all'.
** GET https://github.com/Ensembl/Bio-HTS/archive/master.zip ==> 302 Found
** GET https://codeload.github.com/Ensembl/Bio-HTS/zip/master ==> 200 OK (3s)
 - unpacking ./Bio/tmp/biodbhts.zip to ./Bio/tmp/
./Bio/tmp/Bio-HTS-master - moving files to ./biodbhts
 - making Bio::DB:HTS
Using HTSlib in [path]/ensembl-tools/scripts/variant_effect_predictor/htslib
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '1.05'
Building Bio-DB-HTS
cc -I[path]/ensembl-tools/scripts/variant_effect_predictor/htslib/htslib -I/software/ensembl/central/lib/5.14.2/x86_64-linux-thread-multi/CORE -DXS_VERSION="1.05" -DVERSION="1.05" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wformat=0 -c -D_REENTRANT -D_GNU_SOURCE -DPERL_RELOCATABLE_INCPUSH -fno-strict-aliasing -pipe -fstack-protector -I/software/ensembl/central/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O3 -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
lib/Bio/DB/HTS/Faidx.xs:24:26: fatal error: htslib/faidx.h: No such file or directory
compilation terminated.
error building lib/Bio/DB/HTS/Faidx.o from 'lib/Bio/DB/HTS/Faidx.c' at /nfs/users/nfs_w/wm2/Perl/ExtUtils/CBuilder/Base.pm line 177.
ERROR: Shared Bio::DB:HTS library not found

**Comment by rishidev** [comment]
OK - I'll have a look.

**Comment by rishidev** [comment]
So this was down to a Bio::DB::HTS error which has been fixed. I've tested this installing on my Linux VMs, farm2 and the MacOSX. The code compiles and installs on all of these but there is a failure of the tests on the Mac OSX. The same failures though occur on release 83. I'll update the travis file to refer to this and re-submit the pull request.

**Pull request closed without merging**
